// -----------------------------------------------------------------------------
// Auto-generated by regmap_codegen.py on 2026-05-08 20:09:26
// Source : se_top_regmap_compact.xlsx
// Notes  :
//   1. RW fields are stored inside this regfile.
//   2. RO fields are driven by external *_i inputs.
//   3. WO fields expose *_we_o + *_wdata_o outputs.
//   4. W1C fields are stored internally and OR-ed with *_set_i,
//      then cleared when software writes 1 to the corresponding bits.
// -----------------------------------------------------------------------------
`timescale 1ns / 1ps

module se_top_regfile #(
    parameter ADDR_WIDTH = 32,
    parameter DATA_WIDTH = 32,
    parameter [ADDR_WIDTH-1:0] BASE_ADDR = 32'h00000000
) (
    input  wire                     clk,
    input  wire                     rst_n,
    input  wire                     wr_en,
    input  wire [ADDR_WIDTH-1:0]    wr_addr,
    input  wire [DATA_WIDTH-1:0]    wr_data,
    input  wire                     rd_en,
    input  wire [ADDR_WIDTH-1:0]    rd_addr,
    output reg  [DATA_WIDTH-1:0]    rd_data,
    output wire                     se_ctrl_start_we_o,
    output wire                     se_ctrl_start_wdata_o,
    output wire                     se_ctrl_stop_we_o,
    output wire                     se_ctrl_stop_wdata_o,
    output wire                     se_ctrl_soft_reset_we_o,
    output wire                     se_ctrl_soft_reset_wdata_o,
    output reg                      se_ctrl_irq_en_o,
    output reg  [31:0]              se_boot_pc_o,
    output reg                      se_fetch_cfg_fetch_enable_o,
    output reg  [3:0]               se_fetch_cfg_burst_beats_o,
    output reg  [7:0]               se_fetch_cfg_fifo_waterline_o,
    output reg                      se_mode_single_step_o,
    output reg                      se_mode_trace_en_o,
    output reg                      se_mode_halt_on_illegal_o,
    output reg                      se_mode_halt_on_unsupported_o,
    input  wire                     se_status_running_i,
    input  wire                     se_status_idle_i,
    input  wire                     se_status_fetch_busy_i,
    input  wire                     se_status_decode_hold_i,
    input  wire                     se_status_lsu_pending_i,
    input  wire                     se_status_error_i,
    input  wire [31:0]              se_pc_cur_i,
    input  wire [31:0]              se_pc_last_commit_i,
    input  wire                     se_hold_reason_scalar_raw_i,
    input  wire                     se_hold_reason_scalar_waw_i,
    input  wire                     se_hold_reason_desc_raw_i,
    input  wire                     se_hold_reason_desc_waw_i,
    input  wire                     se_hold_reason_lsu_busy_i,
    input  wire                     se_hold_reason_ts_not_ready_i,
    input  wire                     se_hold_reason_fifo_empty_i,
    input  wire                     se_hold_reason_fifo_full_i,
    input  wire                     se_err_status_illegal_instr_set_i,
    output reg                      se_err_status_illegal_instr_o,
    input  wire                     se_err_status_unsupported_instr_set_i,
    output reg                      se_err_status_unsupported_instr_o,
    input  wire                     se_err_status_mif_error_set_i,
    output reg                      se_err_status_mif_error_o,
    input  wire                     se_err_status_pc_unaligned_set_i,
    output reg                      se_err_status_pc_unaligned_o,
    input  wire                     se_err_status_fifo_overflow_set_i,
    output reg                      se_err_status_fifo_overflow_o,
    input  wire                     se_err_status_fifo_underflow_set_i,
    output reg                      se_err_status_fifo_underflow_o,
    input  wire                     se_err_status_lsu_error_set_i,
    output reg                      se_err_status_lsu_error_o,
    input  wire [31:0]              se_err_pc_i,
    input  wire [31:0]              se_err_inst_i,
    input  wire [2:0]               se_err_info_engine_i,
    input  wire [5:0]               se_err_info_desc_idx_i,
    input  wire [4:0]               se_err_info_rd_i,
    input  wire [4:0]               se_err_info_rs1_i,
    input  wire [4:0]               se_err_info_rs2_i,
    output wire                     se_err_clear_clear_mask_we_o,
    output wire [31:0]              se_err_clear_clear_mask_wdata_o,
    input  wire [31:0]              se_cycle_cnt_l_i,
    input  wire [31:0]              se_cycle_cnt_h_i,
    input  wire [31:0]              se_inst_cnt_l_i,
    input  wire [31:0]              se_inst_cnt_h_i,
    input  wire [31:0]              se_fetch_req_cnt_i,
    input  wire [31:0]              se_fetch_stall_cnt_i,
    input  wire [31:0]              se_decode_hold_cnt_i,
    input  wire [31:0]              se_issue_cnt_vec_i,
    input  wire [31:0]              se_issue_cnt_tensor_i,
    input  wire [31:0]              se_issue_cnt_tma_i,
    input  wire [31:0]              se_issue_cnt_cv_i,
    input  wire [31:0]              se_lsu_req_cnt_i,
    input  wire [31:0]              se_last_inst_i,
    input  wire [5:0]               se_last_desc_idx_i,
    input  wire [2:0]               se_last_issue_info_engine_i,
    input  wire                     se_last_issue_info_issue_valid_i,
    input  wire                     se_last_issue_info_issue_ready_i,
    input  wire [7:0]               se_fifo_level_i,
    output reg  [5:0]               se_desc_dbg_addr_desc_dbg_idx_o,
    input  wire [31:0]              se_desc_dbg_data0_desc_dbg_data_31_0_i,
    input  wire [31:0]              se_desc_dbg_data1_desc_dbg_data_63_32_i,
    input  wire [31:0]              se_desc_dbg_data2_desc_dbg_data_95_64_i,
    input  wire [31:0]              se_desc_dbg_data3_desc_dbg_data_127_96_i,
    input  wire [31:0]              se_desc_dbg_data4_desc_dbg_data_159_128_i,
    input  wire [31:0]              se_desc_dbg_data5_desc_dbg_data_191_160_i,
    input  wire [31:0]              se_desc_dbg_data6_desc_dbg_data_223_192_i,
    input  wire [31:0]              se_desc_dbg_data7_desc_dbg_data_255_224_i
);

localparam [ADDR_WIDTH-1:0] SE_CTRL_ADDR = BASE_ADDR + 32'h00000000;
localparam [ADDR_WIDTH-1:0] SE_BOOT_PC_ADDR = BASE_ADDR + 32'h00000004;
localparam [ADDR_WIDTH-1:0] SE_FETCH_CFG_ADDR = BASE_ADDR + 32'h00000008;
localparam [ADDR_WIDTH-1:0] SE_MODE_ADDR = BASE_ADDR + 32'h0000000C;
localparam [ADDR_WIDTH-1:0] SE_STATUS_ADDR = BASE_ADDR + 32'h00000010;
localparam [ADDR_WIDTH-1:0] SE_PC_CUR_ADDR = BASE_ADDR + 32'h00000014;
localparam [ADDR_WIDTH-1:0] SE_PC_LAST_COMMIT_ADDR = BASE_ADDR + 32'h00000018;
localparam [ADDR_WIDTH-1:0] SE_HOLD_REASON_ADDR = BASE_ADDR + 32'h0000001C;
localparam [ADDR_WIDTH-1:0] SE_ERR_STATUS_ADDR = BASE_ADDR + 32'h00000020;
localparam [ADDR_WIDTH-1:0] SE_ERR_PC_ADDR = BASE_ADDR + 32'h00000024;
localparam [ADDR_WIDTH-1:0] SE_ERR_INST_ADDR = BASE_ADDR + 32'h00000028;
localparam [ADDR_WIDTH-1:0] SE_ERR_INFO_ADDR = BASE_ADDR + 32'h0000002C;
localparam [ADDR_WIDTH-1:0] SE_ERR_CLEAR_ADDR = BASE_ADDR + 32'h00000030;
localparam [ADDR_WIDTH-1:0] SE_CYCLE_CNT_L_ADDR = BASE_ADDR + 32'h00000034;
localparam [ADDR_WIDTH-1:0] SE_CYCLE_CNT_H_ADDR = BASE_ADDR + 32'h00000038;
localparam [ADDR_WIDTH-1:0] SE_INST_CNT_L_ADDR = BASE_ADDR + 32'h0000003C;
localparam [ADDR_WIDTH-1:0] SE_INST_CNT_H_ADDR = BASE_ADDR + 32'h00000040;
localparam [ADDR_WIDTH-1:0] SE_FETCH_REQ_CNT_ADDR = BASE_ADDR + 32'h00000044;
localparam [ADDR_WIDTH-1:0] SE_FETCH_STALL_CNT_ADDR = BASE_ADDR + 32'h00000048;
localparam [ADDR_WIDTH-1:0] SE_DECODE_HOLD_CNT_ADDR = BASE_ADDR + 32'h0000004C;
localparam [ADDR_WIDTH-1:0] SE_ISSUE_CNT_VEC_ADDR = BASE_ADDR + 32'h00000050;
localparam [ADDR_WIDTH-1:0] SE_ISSUE_CNT_TENSOR_ADDR = BASE_ADDR + 32'h00000054;
localparam [ADDR_WIDTH-1:0] SE_ISSUE_CNT_TMA_ADDR = BASE_ADDR + 32'h00000058;
localparam [ADDR_WIDTH-1:0] SE_ISSUE_CNT_CV_ADDR = BASE_ADDR + 32'h0000005C;
localparam [ADDR_WIDTH-1:0] SE_LSU_REQ_CNT_ADDR = BASE_ADDR + 32'h00000060;
localparam [ADDR_WIDTH-1:0] SE_LAST_INST_ADDR = BASE_ADDR + 32'h00000064;
localparam [ADDR_WIDTH-1:0] SE_LAST_DESC_IDX_ADDR = BASE_ADDR + 32'h00000068;
localparam [ADDR_WIDTH-1:0] SE_LAST_ISSUE_INFO_ADDR = BASE_ADDR + 32'h0000006C;
localparam [ADDR_WIDTH-1:0] SE_FIFO_LEVEL_ADDR = BASE_ADDR + 32'h00000070;
localparam [ADDR_WIDTH-1:0] SE_DESC_DBG_ADDR_OFFSET = BASE_ADDR + 32'h00000074;
localparam [ADDR_WIDTH-1:0] SE_DESC_DBG_DATA0_ADDR = BASE_ADDR + 32'h00000078;
localparam [ADDR_WIDTH-1:0] SE_DESC_DBG_DATA1_ADDR = BASE_ADDR + 32'h0000007C;
localparam [ADDR_WIDTH-1:0] SE_DESC_DBG_DATA2_ADDR = BASE_ADDR + 32'h00000080;
localparam [ADDR_WIDTH-1:0] SE_DESC_DBG_DATA3_ADDR = BASE_ADDR + 32'h00000084;
localparam [ADDR_WIDTH-1:0] SE_DESC_DBG_DATA4_ADDR = BASE_ADDR + 32'h00000088;
localparam [ADDR_WIDTH-1:0] SE_DESC_DBG_DATA5_ADDR = BASE_ADDR + 32'h0000008C;
localparam [ADDR_WIDTH-1:0] SE_DESC_DBG_DATA6_ADDR = BASE_ADDR + 32'h00000090;
localparam [ADDR_WIDTH-1:0] SE_DESC_DBG_DATA7_ADDR = BASE_ADDR + 32'h00000094;

wire se_ctrl_wr_hit = wr_en && (wr_addr == SE_CTRL_ADDR);
wire se_boot_pc_wr_hit = wr_en && (wr_addr == SE_BOOT_PC_ADDR);
wire se_fetch_cfg_wr_hit = wr_en && (wr_addr == SE_FETCH_CFG_ADDR);
wire se_mode_wr_hit = wr_en && (wr_addr == SE_MODE_ADDR);
wire se_err_status_wr_hit = wr_en && (wr_addr == SE_ERR_STATUS_ADDR);
wire se_err_clear_wr_hit = wr_en && (wr_addr == SE_ERR_CLEAR_ADDR);
wire se_desc_dbg_addr_wr_hit = wr_en && (wr_addr == SE_DESC_DBG_ADDR_OFFSET);

assign se_ctrl_start_we_o = se_ctrl_wr_hit;
assign se_ctrl_start_wdata_o = wr_data[0];
assign se_ctrl_stop_we_o = se_ctrl_wr_hit;
assign se_ctrl_stop_wdata_o = wr_data[1];
assign se_ctrl_soft_reset_we_o = se_ctrl_wr_hit;
assign se_ctrl_soft_reset_wdata_o = wr_data[2];
assign se_err_clear_clear_mask_we_o = se_err_clear_wr_hit;
assign se_err_clear_clear_mask_wdata_o = wr_data[31:0];

always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
        se_ctrl_irq_en_o <= 1'h0;
        se_boot_pc_o <= 32'h00000000;
        se_fetch_cfg_fetch_enable_o <= 1'h0;
        se_fetch_cfg_burst_beats_o <= 4'h0;
        se_fetch_cfg_fifo_waterline_o <= 8'h00;
        se_mode_single_step_o <= 1'h0;
        se_mode_trace_en_o <= 1'h0;
        se_mode_halt_on_illegal_o <= 1'h0;
        se_mode_halt_on_unsupported_o <= 1'h0;
        se_err_status_illegal_instr_o <= 1'h0;
        se_err_status_unsupported_instr_o <= 1'h0;
        se_err_status_mif_error_o <= 1'h0;
        se_err_status_pc_unaligned_o <= 1'h0;
        se_err_status_fifo_overflow_o <= 1'h0;
        se_err_status_fifo_underflow_o <= 1'h0;
        se_err_status_lsu_error_o <= 1'h0;
        se_desc_dbg_addr_desc_dbg_idx_o <= 6'h00;
    end else begin
        se_err_status_illegal_instr_o <= se_err_status_illegal_instr_o | se_err_status_illegal_instr_set_i;
        se_err_status_unsupported_instr_o <= se_err_status_unsupported_instr_o | se_err_status_unsupported_instr_set_i;
        se_err_status_mif_error_o <= se_err_status_mif_error_o | se_err_status_mif_error_set_i;
        se_err_status_pc_unaligned_o <= se_err_status_pc_unaligned_o | se_err_status_pc_unaligned_set_i;
        se_err_status_fifo_overflow_o <= se_err_status_fifo_overflow_o | se_err_status_fifo_overflow_set_i;
        se_err_status_fifo_underflow_o <= se_err_status_fifo_underflow_o | se_err_status_fifo_underflow_set_i;
        se_err_status_lsu_error_o <= se_err_status_lsu_error_o | se_err_status_lsu_error_set_i;
        if (se_ctrl_wr_hit) begin
            se_ctrl_irq_en_o <= wr_data[3];
        end
        if (se_boot_pc_wr_hit) begin
            se_boot_pc_o <= wr_data[31:0];
        end
        if (se_fetch_cfg_wr_hit) begin
            se_fetch_cfg_fetch_enable_o <= wr_data[0];
            se_fetch_cfg_burst_beats_o <= wr_data[7:4];
            se_fetch_cfg_fifo_waterline_o <= wr_data[15:8];
        end
        if (se_mode_wr_hit) begin
            se_mode_single_step_o <= wr_data[0];
            se_mode_trace_en_o <= wr_data[1];
            se_mode_halt_on_illegal_o <= wr_data[2];
            se_mode_halt_on_unsupported_o <= wr_data[3];
        end
        if (se_err_status_wr_hit) begin
            se_err_status_illegal_instr_o <= (se_err_status_illegal_instr_o | se_err_status_illegal_instr_set_i) & ~wr_data[0];
            se_err_status_unsupported_instr_o <= (se_err_status_unsupported_instr_o | se_err_status_unsupported_instr_set_i) & ~wr_data[1];
            se_err_status_mif_error_o <= (se_err_status_mif_error_o | se_err_status_mif_error_set_i) & ~wr_data[2];
            se_err_status_pc_unaligned_o <= (se_err_status_pc_unaligned_o | se_err_status_pc_unaligned_set_i) & ~wr_data[3];
            se_err_status_fifo_overflow_o <= (se_err_status_fifo_overflow_o | se_err_status_fifo_overflow_set_i) & ~wr_data[4];
            se_err_status_fifo_underflow_o <= (se_err_status_fifo_underflow_o | se_err_status_fifo_underflow_set_i) & ~wr_data[5];
            se_err_status_lsu_error_o <= (se_err_status_lsu_error_o | se_err_status_lsu_error_set_i) & ~wr_data[6];
        end
        if (se_desc_dbg_addr_wr_hit) begin
            se_desc_dbg_addr_desc_dbg_idx_o <= wr_data[5:0];
        end
    end
end

always @* begin
    rd_data = {DATA_WIDTH{1'b0}};
    if (rd_en) begin
        case (rd_addr)
            SE_CTRL_ADDR: begin
                rd_data[3] = se_ctrl_irq_en_o;
            end
            SE_BOOT_PC_ADDR: begin
                rd_data[31:0] = se_boot_pc_o;
            end
            SE_FETCH_CFG_ADDR: begin
                rd_data[0] = se_fetch_cfg_fetch_enable_o;
                rd_data[7:4] = se_fetch_cfg_burst_beats_o;
                rd_data[15:8] = se_fetch_cfg_fifo_waterline_o;
            end
            SE_MODE_ADDR: begin
                rd_data[0] = se_mode_single_step_o;
                rd_data[1] = se_mode_trace_en_o;
                rd_data[2] = se_mode_halt_on_illegal_o;
                rd_data[3] = se_mode_halt_on_unsupported_o;
            end
            SE_STATUS_ADDR: begin
                rd_data[0] = se_status_running_i;
                rd_data[1] = se_status_idle_i;
                rd_data[2] = se_status_fetch_busy_i;
                rd_data[3] = se_status_decode_hold_i;
                rd_data[4] = se_status_lsu_pending_i;
                rd_data[5] = se_status_error_i;
            end
            SE_PC_CUR_ADDR: begin
                rd_data[31:0] = se_pc_cur_i;
            end
            SE_PC_LAST_COMMIT_ADDR: begin
                rd_data[31:0] = se_pc_last_commit_i;
            end
            SE_HOLD_REASON_ADDR: begin
                rd_data[0] = se_hold_reason_scalar_raw_i;
                rd_data[1] = se_hold_reason_scalar_waw_i;
                rd_data[2] = se_hold_reason_desc_raw_i;
                rd_data[3] = se_hold_reason_desc_waw_i;
                rd_data[4] = se_hold_reason_lsu_busy_i;
                rd_data[5] = se_hold_reason_ts_not_ready_i;
                rd_data[6] = se_hold_reason_fifo_empty_i;
                rd_data[7] = se_hold_reason_fifo_full_i;
            end
            SE_ERR_STATUS_ADDR: begin
                rd_data[0] = se_err_status_illegal_instr_o;
                rd_data[1] = se_err_status_unsupported_instr_o;
                rd_data[2] = se_err_status_mif_error_o;
                rd_data[3] = se_err_status_pc_unaligned_o;
                rd_data[4] = se_err_status_fifo_overflow_o;
                rd_data[5] = se_err_status_fifo_underflow_o;
                rd_data[6] = se_err_status_lsu_error_o;
            end
            SE_ERR_PC_ADDR: begin
                rd_data[31:0] = se_err_pc_i;
            end
            SE_ERR_INST_ADDR: begin
                rd_data[31:0] = se_err_inst_i;
            end
            SE_ERR_INFO_ADDR: begin
                rd_data[2:0] = se_err_info_engine_i;
                rd_data[8:3] = se_err_info_desc_idx_i;
                rd_data[13:9] = se_err_info_rd_i;
                rd_data[18:14] = se_err_info_rs1_i;
                rd_data[23:19] = se_err_info_rs2_i;
            end
            SE_ERR_CLEAR_ADDR: begin
            end
            SE_CYCLE_CNT_L_ADDR: begin
                rd_data[31:0] = se_cycle_cnt_l_i;
            end
            SE_CYCLE_CNT_H_ADDR: begin
                rd_data[31:0] = se_cycle_cnt_h_i;
            end
            SE_INST_CNT_L_ADDR: begin
                rd_data[31:0] = se_inst_cnt_l_i;
            end
            SE_INST_CNT_H_ADDR: begin
                rd_data[31:0] = se_inst_cnt_h_i;
            end
            SE_FETCH_REQ_CNT_ADDR: begin
                rd_data[31:0] = se_fetch_req_cnt_i;
            end
            SE_FETCH_STALL_CNT_ADDR: begin
                rd_data[31:0] = se_fetch_stall_cnt_i;
            end
            SE_DECODE_HOLD_CNT_ADDR: begin
                rd_data[31:0] = se_decode_hold_cnt_i;
            end
            SE_ISSUE_CNT_VEC_ADDR: begin
                rd_data[31:0] = se_issue_cnt_vec_i;
            end
            SE_ISSUE_CNT_TENSOR_ADDR: begin
                rd_data[31:0] = se_issue_cnt_tensor_i;
            end
            SE_ISSUE_CNT_TMA_ADDR: begin
                rd_data[31:0] = se_issue_cnt_tma_i;
            end
            SE_ISSUE_CNT_CV_ADDR: begin
                rd_data[31:0] = se_issue_cnt_cv_i;
            end
            SE_LSU_REQ_CNT_ADDR: begin
                rd_data[31:0] = se_lsu_req_cnt_i;
            end
            SE_LAST_INST_ADDR: begin
                rd_data[31:0] = se_last_inst_i;
            end
            SE_LAST_DESC_IDX_ADDR: begin
                rd_data[5:0] = se_last_desc_idx_i;
            end
            SE_LAST_ISSUE_INFO_ADDR: begin
                rd_data[2:0] = se_last_issue_info_engine_i;
                rd_data[3] = se_last_issue_info_issue_valid_i;
                rd_data[4] = se_last_issue_info_issue_ready_i;
            end
            SE_FIFO_LEVEL_ADDR: begin
                rd_data[7:0] = se_fifo_level_i;
            end
            SE_DESC_DBG_ADDR_OFFSET: begin
                rd_data[5:0] = se_desc_dbg_addr_desc_dbg_idx_o;
            end
            SE_DESC_DBG_DATA0_ADDR: begin
                rd_data[31:0] = se_desc_dbg_data0_desc_dbg_data_31_0_i;
            end
            SE_DESC_DBG_DATA1_ADDR: begin
                rd_data[31:0] = se_desc_dbg_data1_desc_dbg_data_63_32_i;
            end
            SE_DESC_DBG_DATA2_ADDR: begin
                rd_data[31:0] = se_desc_dbg_data2_desc_dbg_data_95_64_i;
            end
            SE_DESC_DBG_DATA3_ADDR: begin
                rd_data[31:0] = se_desc_dbg_data3_desc_dbg_data_127_96_i;
            end
            SE_DESC_DBG_DATA4_ADDR: begin
                rd_data[31:0] = se_desc_dbg_data4_desc_dbg_data_159_128_i;
            end
            SE_DESC_DBG_DATA5_ADDR: begin
                rd_data[31:0] = se_desc_dbg_data5_desc_dbg_data_191_160_i;
            end
            SE_DESC_DBG_DATA6_ADDR: begin
                rd_data[31:0] = se_desc_dbg_data6_desc_dbg_data_223_192_i;
            end
            SE_DESC_DBG_DATA7_ADDR: begin
                rd_data[31:0] = se_desc_dbg_data7_desc_dbg_data_255_224_i;
            end
            default: begin
                rd_data = {DATA_WIDTH{1'b0}};
            end
        endcase
    end
end

endmodule
